spring:
  #数据库驱动配置信息 
  datasource:
  #sqlserver数据源
  #  url: jdbc:sqlserver://localhost:52409;DatabaseName=sino_test
  #  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #  username: saoa  
  #  password: saoa123456
    
    url: jdbc:mysql://rm-bp19984lh2msb1xyyoo.mysql.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong 
    driverClassName : com.mysql.jdbc.Driver
    username: root  
    password: Dongxiang0607!
  # ES
  #开启 Elasticsearch 仓库(默认值:true)
  data:
    elasticsearch:
      repositories:
        enabled: true
      #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      cluster-name: elasticsearch
      cluster-nodes: 59.110.163.229:9300
#      properties: 
#        path:
#          home: /data/project/target/elastic
#        transport:
#          tcp:
#            connect_timeout: 120s
    
  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis: 
    database: 0
    # Redis服务器地址
    host: 59.110.163.229
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: dongxiang.
    # 连接超时时间（毫秒）
    timeout: 0s
    # 连接池最大连接数（使用负值表示没有限制）
#    pool:
#      max-active: 8
#    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#    # 连接池中的最大空闲连接
#      max-idle: 8
#    # 连接池中的最小空闲连接
#      min-idle: 0
   
   
    
    
server:
  #端口号
  port: 8180
  mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
  #session最大超时时间（默认30分钟）
  session: 60
  tomcat:
    #tomcat的uri编码
    uri-encoding: utf-8
    
  