spring:
  #数据库驱动配置信息 
  datasource:
  #sqlserver数据源
  #  url: jdbc:sqlserver://localhost:52409;DatabaseName=sino_test
  #  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #  username: saoa  
  #  password: saoa123456
    
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong 
    driverClassName : com.mysql.jdbc.Driver
    username: root  
    password: root
  # ES
  #开启 Elasticsearch 仓库(默认值:true)
  data:
    elasticsearch:
      repositories:
        enabled: true
      #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      cluster-name: es-master
      cluster-nodes: 172.16.200.68:9300
#      properties: 
#        path:
#          home: /data/project/target/elastic
#        transport:
#          tcp:
#            connect_timeout: 120s
    
    
server:
  #端口号
  port: 8180
  mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
  #session最大超时时间（默认30分钟）
  session: 60
  tomcat:
    #tomcat的uri编码
    uri-encoding: utf-8
    
  